- protos/orchestrator_service.proto
Rename GRPC protobuf package to com.microsoft.durabletask.implementation.protobuf as this is for internal use and not public API.
> update protobuf package name

- protos/orchestrator_service.proto
This will let implementations (optionally) implement Rewind functionality. DTFx Core does not support rewind natively yet. This will let Durable Functions isolated support this functionality right away without waiting on official DTFx Core support.
> Add RewindInstance RPC definition

- protos/orchestrator_service.proto
Currently suspend/resume is only supported for .NET in-process. This gRPC change is required to support it for out-of-process architectures.
> Add suspend and resume operations

- protos/orchestrator_service.proto
Adds required protocols for supporting entities. This includes requests/responses for client-initiated entity-related operations, and the new workitem definitions for entity work items.
> Add entity support

- protos/orchestrator_service.proto
Two minor fixes:
- `serializedState` must allow null because queries can ask for  the state to not be included.
- forgot to serialize/deserialize the `failureDetails` field as part of the `EntityBatchResult` data structure.
> small fixes to entity support

- protos/orchestrator_service.proto
This PR adds support for flowing distributed trace information through orchestrations that use protobuf serialization (including out-of-proc languages in Durable Functions).
This has been tested using the `durabletask-go` project, which uses the protobufs in this repo extensively for all state serialization. Tested scenarios include activity chaining, activity fan-out/fan-in, timers, and continue-as-new. The PR includes support for sub-orchestration history events as well, but this hasn't been tested yet. The corresponding PR that uses these changes can be found here: https://github.com/microsoft/durabletask-go/pull/2
Note that these changes should *roughly* match the code changes needed in the history events in the .NET Durable Task Framework.
> Initial support for distributed tracing

- protos/orchestrator_service.proto
`GenericEvent` is currently used in rewind logic to store the rewind reason. Currently, if no reason is provided it will throw null value exception. It should allow the user to rewind their orchestration without providing a reason. 
TODO: validate if it could be a breaking change.
> Update `GenericEvent` to accept null value

- protos/orchestrator_service.proto
This PR update grpc proto to allow customers to pass `InstanceExistOption` when creating a new orchestrator. 
More info please refer to https://github.com/microsoft/durabletask-go/issues/42
> Support orchestration id reuse policies

- protos/backend_service.proto
- protos/orchestrator_service.proto
This PR defines a new gRPC service for a remote backend implementation for the Durable Task Framework (DTFx). It depends on many of the existing message types from `orchestration_service.proto`, such as event history definitions, but defines a few new message types as well.
Implementations of this RPC could be used to build client and server components for custom DTFx backends.
> Backend service RPCs

- protos/orchestrator_service.proto
Add parent trace context to `ActivityRequest ` to support tracing in Task. 
Issue: https://github.com/microsoft/durabletask-go/issues/31
> Add trace context to activity request

- protos/backend_service.proto
Created a new API in `backend_service.proto` called `GetMetrics`, which returns a metrics payload to the caller. The intended use case is for backend clients to fetch metrics that can be used for making dynamic scale decisions.
> Adding GetMetrics RPC to backend service contract

- protos/orchestrator_service.proto
Adding fields so a client that connects to the backend can inform the backend about the maximum number of concurrent orchestration and activity work items it can handle.
This is useful for implementing server-side flow control for work items.
> add concurrency limits to GetWorkItemsRequest

- protos/orchestrator_service.proto
This PR adds `completionToken` fields to the `ActivityResponse` and `OrchestratorResponse` messages in the `protos/orchestrator_service.proto` file. SDKs using these message types should populate these fields with the `completionToken` value of the corresponding `WorkItem` message received from the sidecar/backend.
This change is needed for better correlation of completions and work items.
Also included in this PR are some whitespace formatting fixes.
> Add completion token fields to activity and orchestrator response messages

- protos/backend_service.proto
- protos/orchestrator_service.proto
This PR adds a `StreamInstanceHistory` API to both the `BackendService` and `TaskHubSidecarService` services in the `protos` directory. The purpose of these APIs is to allow a worker to get the history of an orchestration as a series of one-way messages to avoid exceeding gRPC message size limits.
With this change, the backend service can now return orchestrator work items that exclude the history if the history is known to be too large. When it does this, it should set the `requiresHistoryStreaming` field to true so that the worker can distinguish between no history and omitted history. Workers opt into this behavior change by setting a new `GetWorkItemsRequest.supportsHistoryStreaming` field.
This PR also introduces a new `numEventsProcessed` field to …
> History streaming API additions

- protos/orchestrator_service.proto
This change adds a `ParentTraceContext` field to `CreateInstanceRequest` in the `protos
/orchestrator_service.proto` file. It helps us link the client and orchestrator function spans as a parent-child relationship in Durable Functions .NET Isolated distributed traces.
> Add TraceContext to CreateInstanceRequest

- protos/orchestrator_service.proto
adds an orchestrator action for sending messages (signal, call, lock, unlock) to entities.
This is needed by the following PR: https://github.com/microsoft/durabletask-dotnet/pull/369
> Add orchestrator actions for entity messages

- protos/orchestrator_service.proto
As discussed:
- renaming the `operationStatus` field to clarify polarity of list
- removing the obsolete `action` field (reserving its key, as recommended when deleting protobuf fields).
> simplify orchestration id reuse policy

- protos/orchestrator_service.proto
Abandon APIs were added to the orchestration proto based on the implementations (input/output) I had seen in existing backends.
> Add abandon APIs to orchestration proto

- protos/orchestrator_service.proto
This PR adds a new map field named `properties` to `OrchestratorRequest`
We are adding a new Dictionary <string, object> at TaskorcehstrationContext in Microsoft.DurableTask. This new field will allow configuration from DurableTaskOptions at WebJobs.Extensions.DurableTasdk can be passed to this dictionary in `TaskOrchestrationContext`
Related PR https://github.com/Azure/azure-functions-durable-extension/pull/3092
> Add properties Field to OrchestratorRequest

- protos/orchestrator_service.proto
This pull request makes a minor update to the `protos/orchestrator_service.proto` file by adding a new import statement for `google/protobuf/struct.proto`. This change likely supports additional functionality or data structures in the protocol buffer definitions.
> add missing import for google.protobuf.Value

- protos/orchestrator_service.proto
part of change required for activity tagging
This pull request updates the `protos/orchestrator_service.proto` file to include support for `tags` in task-related messages. These changes enhance the protocol buffer definitions to allow additional metadata to be associated with tasks.
* [`message TaskScheduledEvent`](diffhunk://#diff-1a29f05d707748da230a5e02a23225ece4272a3cbf247817ae47dc673f466150R98): Added a `tags` field of type `map<string, string>` to allow attaching metadata to scheduled tasks.
* [`message ScheduleTaskAction`](diffhunk://#diff-1a29f05d707748da230a5e02a23225ece4272a3cbf247817ae47dc673f466150R260): Added a `tags` field of type `map<string, string>` to support metadata for task scheduling actions.
> Add tags field to TaskScheduledEvent and ScheduleTaskAction in orchestrator_service.proto

- protos/orchestrator_service.proto
This PR adds new fields to protobuf objects related to signaling entities or entities starting an orchestration to correctly enable distributed tracing for entities in the .NET isolated framework. The fields propagate parent trace context information to make sure that the traces are correctly linked together (i.e. that the trace corresponding to a signal entity request becomes the parent of the trace corresponding to that request being processed). They also propagate the time a request was created or completed in order to correctly set the start and end time of the corresponding traces. 
The various other PRs related to this effort are
- [WebJobs](https://github.com/Azure/azure-functions-durable-extension/pull/3076)
- [durabletask-dotnet](https://github.com/microsoft/durabletask-dotnet/pul …
> Distributed Tracing for Entities (Isolated)

- protos/orchestrator_service.proto
This PR is part of support of issue https://github.com/Azure/azure-functions-durable-extension/issues/2903
This PR adds a new `RestartInstance` RPC method to the TaskHubSidecarService that allows restarting orchestration instances with provided instanceId or a new instanceId. 
Updates:
- Add `RestartInstanceRequest` message with `instanceId` and `restartWithNewInstanceId` fields
- Add RestartInstance RPC method that receives `RestartInstanceRequest`  and returns `CreateInstanceResponse`
> Add RestartInstance RPC method to orchestrator service

- protos/orchestrator_service.proto
This PR adds a new `historyRequired` field to the `OrchestratorResponse`. This will be used by the dotnet SDK to handle the edge case where it has since ended an extended session and needs an orchestration history in order to replay the orchestration up to the execution point, but none was provided in the `OrchestratorRequest`. The SDK will set the `historyRequired` field in the response to true, in which case the host will end the extended session and attach a history in the next `OrchestratorRequest` (specifically, as discussed in this [PR](https://github.com/Azure/azure-functions-durable-extension/pull/3154), the [`OutOfProcMiddleware`](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/WebJobs.Extensions.DurableTask/OutOfProcMiddleware.cs) class will check for …
> Extended Sessions for Isolated (Orchestrations)

- protos/orchestrator_service.proto
This PR introduces a new `InstanceBatch` type to be leveraged across several batch actions. It changes the current `SkipGracefulOrchestrationTerminationsRequest` to use this type, and makes it one of the options for the `PurgeInstancesRequest` as well.
> Add InstanceBatch and Batch Purge
